# Site settings
title: Methods 3 – Fall 2018
email:
description: > # this means to ignore newlines until "baseurl:"
  This website displays student projects from the Design and Urban Ecologies
  Methods 3 class – Fall 2018.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://due-parsons.github.io/methods3-fall2018" # the base hostname & protocol for your site
twitter_username:
github_username:  DUE-Parsons

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
